server:
  servlet:
    session:
      timeout: 168h
      cookie:
        name: Promisesd
        http-only: true
        secure: true
  ssl:
    enabled: true
    key-store: keystore.p12
    store-type: PKCS12
    key-store-password: ENC(KDwwPa2O5brW2wkhJQAuNL7+kH/JVan7tiaS0is2/dLNb4fiefGzI85QDJcZZWLbpTlZX08wLjkg5ny7ihNqSz/YHDHBbKtym0xzuotZ0nk5Oak4KQnMWA8jNoUWPK2yRCFH3Gkh++DoWR26Bu1Gug==)
  port: 4400
  http-port: 8800

config.sitemap.path: resources/serves/sitemap.xml
config.robot.path: resources/serves/robots.txt
docs.mappingFile: resources/docsMapping.json

db:
  identification:
    url: ENC(a/JBDDrD5B5dc5XvQeIvHwHzrtxFekyDo5wkPeVLejDyQm547zO5deHd7zYa2bJVwUuH2RDTblpYYE7+d1ak/HF50yuQriEnlByCcbePSBM=)
    username: ENC(mPSmJTPUPoe9xaUGdNbbFd3ygmKoNqEBjW9dQF0cVoQNLwHRow8gTpxPJGtediox)
    password: ENC(L4lv3cfQ6ik2xmdKUZuhVsRSxE99d+x4CQGK1NjK/gZWBjjfcaVm8Q/BduTaWy/+3uGeGgpJhr6wbbvl7vzXyytq05cUdzeP3vAm31KvkSf8mK23YepJKOv9hyFdlJ9VAZQLcx0phB3GzGrZGm544Q==)
  problem:
    url: ENC(rCoYxhOvKIgswXtEZ3siNnvhTdZplaSO0ldQbukpAGGa6u73Otm1e8CEarlmAVcxer1pb/l54RXTb4FHW9kP50byEnZPgd4thWwi6SsnfpI=)
    username: ENC(mPSmJTPUPoe9xaUGdNbbFd3ygmKoNqEBjW9dQF0cVoQNLwHRow8gTpxPJGtediox)
    password: ENC(L4lv3cfQ6ik2xmdKUZuhVsRSxE99d+x4CQGK1NjK/gZWBjjfcaVm8Q/BduTaWy/+3uGeGgpJhr6wbbvl7vzXyytq05cUdzeP3vAm31KvkSf8mK23YepJKOv9hyFdlJ9VAZQLcx0phB3GzGrZGm544Q==)
  invite:
    url: ENC(K7IOx54h7/hUi1JKi26EiXQCeN/zTCCESOhb/GL03pAR3X+9ry72AtdQkzuRHz0QPQ0E9jR9yS9hRf1PRkVBPuBu4bvN2DtRV1b/j2bJHyY=)
    username: ENC(mPSmJTPUPoe9xaUGdNbbFd3ygmKoNqEBjW9dQF0cVoQNLwHRow8gTpxPJGtediox)
    password: ENC(L4lv3cfQ6ik2xmdKUZuhVsRSxE99d+x4CQGK1NjK/gZWBjjfcaVm8Q/BduTaWy/+3uGeGgpJhr6wbbvl7vzXyytq05cUdzeP3vAm31KvkSf8mK23YepJKOv9hyFdlJ9VAZQLcx0phB3GzGrZGm544Q==)
  solution:
    url: ENC(+h9l6wr/7z91l8X/bBPNmw5avejt5C1zLRVOf1+FiihObMdn1wNTDvJLFY0w6mEceIbr3aLBmpIlNb/lD810al9IB2rSD6nerlWmOiAYwVk=)
    username: ENC(mPSmJTPUPoe9xaUGdNbbFd3ygmKoNqEBjW9dQF0cVoQNLwHRow8gTpxPJGtediox)
    password: ENC(L4lv3cfQ6ik2xmdKUZuhVsRSxE99d+x4CQGK1NjK/gZWBjjfcaVm8Q/BduTaWy/+3uGeGgpJhr6wbbvl7vzXyytq05cUdzeP3vAm31KvkSf8mK23YepJKOv9hyFdlJ9VAZQLcx0phB3GzGrZGm544Q==)

captcha:
  v3:
    sitekey: 6LdcHUAcAAAAANVctCmNgQ1w9ZIbHl5wv-N6EYGE
    secret: ENC(ZLUKnyVfUgYnNiL2FGb4t52C3U+Rhy6B9O+wtcku0fWAVmfXogfLhikYRTFxRgbsvj5zRziZP4ZvoSDtaGC8wXVuJy9eQo8CJPeVvoFA1FI=)
  v2:
    sitekey: 6LcEQUAcAAAAAAYOVwrByX_OZs6-fyZbGV46nkoK
    secret: ENC(Bq+4is0NfuOtjcONleLLQ2A9DyDALUSSwnkLlhgeNPOP+1lh/wMMlxCL5s7HsamSQa5C1kpKPiZfVptGgwBOV77/hmbl2oTGdgolfjSCZzs=)

ipu:
  access:
    force-login-for-problem: true

spring:
  thymeleaf:
    cache: true
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false