server:
  servlet:
    session:
      timeout: 168h
      cookie:
        name: Promisesd
        http-only: true
        secure: true
  ssl:
    enabled: true
    key-store: keystore.p12
    store-type: PKCS12
    key-store-password: ENC(KDwwPa2O5brW2wkhJQAuNL7+kH/JVan7tiaS0is2/dLNb4fiefGzI85QDJcZZWLbpTlZX08wLjkg5ny7ihNqSz/YHDHBbKtym0xzuotZ0nk5Oak4KQnMWA8jNoUWPK2yRCFH3Gkh++DoWR26Bu1Gug==)
  port: 4400
  http-port: 8800

config.sitemap.path: resources/serves/sitemap.xml
config.robot.path: resources/serves/robots.txt
docs.mappingFile: resources/docsMapping.json

db:
  identification:
    url: jdbc:postgresql://localhost:5432/identification
    username: ENC(bjwHiiIti9hI7QfDvdDkHQ4CCEt8LFwpWFu54Dk6b6caVpKV/KVU1w/eY/g9Qvca)
    password: ENC(yRG2nJUsih22Z0vGX2rKpZgkfiBRmUUXHpC9xNxFCF6RUHaQHBYg2VOeu6BydN7P)
  problem:
    url: jdbc:postgresql://localhost:5432/problem
    username: ENC(lxXIHLICd7tfW17qMz1lN1THDrHITBddgnyCSJYwGMDDR0n9UfzrFgsLnSGOySwX)
    password: ENC(ukSuagnZIUcev/8v125f7+epWhKCVkw0mA2YTG6EULLyaqzelbfmjUkixAjVMbqG)
  invite:
    url: jdbc:postgresql://localhost:5432/invite
    username: ENC(5YI5toVnfFFWtq40VUAc0njuKv8IWWgRiKjBdRS0UGbQTv3bMU2v5MtgSNqn3wlt)
    password: ENC(qONxcaGxLHFqxnxqcmZQnRtLq3vdwMWelyqwuk2zFRaYz+CdYLud19uHBmFXCR7e)

captcha:
  v3:
    sitekey: 6LdcHUAcAAAAANVctCmNgQ1w9ZIbHl5wv-N6EYGE
    secret: ENC(ZLUKnyVfUgYnNiL2FGb4t52C3U+Rhy6B9O+wtcku0fWAVmfXogfLhikYRTFxRgbsvj5zRziZP4ZvoSDtaGC8wXVuJy9eQo8CJPeVvoFA1FI=)
  v2:
    sitekey: 6LcEQUAcAAAAAAYOVwrByX_OZs6-fyZbGV46nkoK
    secret: ENC(Bq+4is0NfuOtjcONleLLQ2A9DyDALUSSwnkLlhgeNPOP+1lh/wMMlxCL5s7HsamSQa5C1kpKPiZfVptGgwBOV77/hmbl2oTGdgolfjSCZzs=)

ipu:
  access:
    force-login-for-problem: true

# Debug
spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true