name: GCP distribute

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Starter
      - run: echo Action Started
      - name: Change to repository path
        run: |
          cd ${{ github.workspace }}
      
