name: GCP distribute

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Change to repository path
        run: |
          cd ${{ github.workspace }}

      - name: Archieve files to tar
      - run: tar -czf ipu.tar.gz views server.js server-component/ robots.txt  package.json package-lock.json  library/ invites.json
      
