name: GCP distribute

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Distribute
        run: |
          echo Action Started
          cd ${{ github.workspace }}
          pwd
          ls ${{ github.workspace }}
