name: GCP distribute

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: distribute
        run: |
          tar -czf t.tar.gz views server.js server-component/ robots.txt  package.json package-lock.json  library/ invites.json
