name: GCP distribute

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Change to repository path
        run: |
          cd ${{ github.workspace }}
          ls
      - name: Archieve files to tar
      - run: tar -czf ipu.tar.gz views server.js server-component/ robots.txt  package.json package-lock.json  library/ invites.json
      - name: Upload to FTP
        run: |
          ftp -p lucys.r-e.kr
          ${{secrets.FTP_USER_NAME}}
          ${{secrets.FTP_USER_PASSWORD}}
          put ipu.tar.gz
          quit
          echo FTP uploaded
