name: Distribute to server

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Build_and_distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Prepare to sync
        run: |
          mkdir to_be_sync
          cp -r ./{resources,build/libs/IPU-3.0.0.jar} ./to_be_sync
          mv to_be_sync/IPU-3.0.0.jar to_be_sync/IPU.jar
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: lucys.r-e.kr
          username: ${{ secrets.FTP_USER_NAME }}
          password: ${{ secrets.FTP_USER_PASSWORD }}
          protocol: ftps
          local-dir: ./to_be_sync/
          server-dir: ./ipu/
      - name: action-slack
        uses: 8398a7/action-slack@v3.12.0
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `커밋 ${process.env.AS_COMMIT}에 대한 배포작업이 끝났어요.\n결과: ${{ job.status }} in ${process.env.AS_TOOK}\n`,
              }]
            }
          author_name: "개발요정"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

