name: GCP distribute

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Distribute
        run: |
          echo Action Started
          cd ${{ github.workspace }}
          tar -czf ipu.tar.gz ${{ github.workspace }}/views ${{ github.workspace }}/server.js ${{ github.workspace }}/server-component/ ${{ github.workspace }}/robots.txt ${{ github.workspace }}/package.json ${{ github.workspace }}/package-lock.json  ${{ github.workspace }}/library/ ${{ github.workspace }}/invites.json
