name: GCP distribute

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Change to repository path
        run: |
          cd ${{ github.workspace }}
          ls .
          ls ${{ github.workspace }}
